### ISSUE TITLE
Missing Images when loading from unpkg.com

### ISSUE THREAD

**Issue by spiderbytes** [khang-nd/7.css#10]
Hello,

when I load the CSS from unpkg.com, the images (for example minimize.png, maximize.png and close.png for the Windows title bar) are missing.

Thanks in Advance & Greetings ... Peter

**Comment by khang-nd** [comment]
I still don't know how they don't show up for you, because the images are there with CDN: https://unpkg.com/browse/7.css@0.4.1/dist/

**Comment by spiderbytes** [comment]
Hello @khang-nd,

oh, I didn't know that the images were also deposited in the CDN. After researching, I found out that the system I use here to create web apps embeds your CSS incorrectly. After I corrected this, everything works as expected.

Sorry for the inconvenience! 😳

**Comment by khang-nd** [comment]
@spiderbytes No problem at all, glad it worked out for you.
