### ISSUE TITLE
make window buttons better

### ISSUE THREAD

**Issue by cyan-2048** [khang-nd/7.css#20]
https://msfn.org/board/uploads/post-383443-0-34934800-1383873674.png #

**Comment by cyan-2048** [comment]
https://msfn.org/board/topic/170233-aero-glass-themeatlas/page/46/

**Comment by cyan-2048** [comment]
i think this atlas file also mimics the shadows more accurately....

**Comment by khang-nd** [comment]
Thanks for sharing, definitely a good reference source.
