### ISSUE TITLE
MessageBox

### ISSUE THREAD

**Issue by HayderYousifIbrahim** [khang-nd/7.css#21]
how to create MessageBox ? I tried creating Dialog box but I couldn't show the dialog using js

**Comment by khang-nd** [comment]
Could you please share your attempted code? On another note, the Dialog Box component is just a trick without JS, you would have to handle the proper JS logic for that by yourself.

**Comment by HayderYousifIbrahim** [comment]
thank you for your replay 

this code is part of login php page 

	$q = $pdo->query($sql);
	$q->setFetchMode(PDO::FETCH_ASSOC);
	$row = $q->fetch();
	if(empty($row)){
	?>
  <script>
    //alert('Invalid user name or password');
    var x = document.getElementById("invalidUserDialog");
    if (x.style.display === "none") {
      x.style.display = "block";
    } 
  </script>
<?php

while the dialog box is

<div dir="rtl" class="window is-bright" id="invalidUserDialog" role="dialog" aria-labelledby="dialog-title">
  <div class="title-bar">
    <div class="title-bar-text" id="dialog-title">تسجيل الدخول</div>
    <div class="title-bar-controls">
      <button aria-label="Close" onclick="history.back()"></button>
    </div>
  </div>
  <div class="window-body">
    <h1>اسم المستخدم او كلمة المرور غير صحيحة</h1>
  </div>
  <footer style="text-align: right">
    <button onclick="history.back()">الغاء</button>
    <button onclick=document.loginForm.submit()>دخول</button>
  </footer>

**Comment by khang-nd** [comment]
Yep, I figured. This issue is not related to this library, you probably want to seek help related to JS somewhere else, sorry but I cannot help.
