### ISSUE TITLE
Icon for help titlebar button missing.

### ISSUE THREAD

**Issue by AestheticalZ** [khang-nd/7.css#31]

**Comment by khang-nd** [comment]
Hi, could you please elaborate?

**Comment by qoomBert** [comment]
There is a window control missing in 7.css, but present in XP.css and 98.css .
There's a question mark button in windows, windows 7 included.
Examples:
VirtualBox:
![helpexample1](https://github.com/khang-nd/7.css/assets/139391744/c3f5cd54-936c-45ec-9d45-791f7b242b21)
Internet Options:
![helpexample2](https://github.com/khang-nd/7.css/assets/139391744/522c6014-4755-4449-8d49-17fba1c9da58)

Its older function is when pressed, show information about a certain element after the element was clicked.
Its newer function is just to open the help program when clicked.

Direct rip of window decor graphics from the theme file:
![STREAM971](https://github.com/khang-nd/7.css/assets/139391744/41c3603d-d870-42fb-b4ee-7cb136e7e6d8)
