### ISSUE TITLE
Flexible font sizing

### ISSUE THREAD

**Issue by swarmukhdefault** [khang-nd/7.css#32]
Currently font sizes for control elements (e.g. buttons) are hard-coded to 9pt. It'd be better to apply `em` and `rem` unit throughout for font sizing. Although, it is a "faithful reproduction", I believe that this request might actually result in enhanced accessibility.

**Comment by khang-nd** [comment]
You've got a point, though I would not change it, as you have said, this aims to follow as closely as possible with the Win32 design guidelines. Though as mentioned at the very top of the docs, you're welcome to override any styling to adapt to your context, it should be easy to do.
