### ISSUE TITLE
Accommodate shortcut mnemonics in menuitems

### ISSUE THREAD

**Issue by swarmukhdefault** [khang-nd/7.css#34]

**Comment by khang-nd** [comment]
Hi, might need some elaboration so I can think of a way to tackle this

**Comment by swarmukhdefault** [comment]
Hi @khang-nd, I've added a screenshot. Although they are using Java Swing look-n-feel, the idea is similar, wherein the shortcut accelerators, i.e. `Ctrl + X`, `Ctrl + Z`, etc. are on the rightmost side of each menu-item

![image](https://user-images.githubusercontent.com/100758771/198819422-06193c63-d8da-4f42-9d04-6392500c6031.png)

**Addendum:** The text on each menu-item i.e. `Undo`, `Redo`, etc, should have a max-width of `x px` with text-clipping enabled. This is required and is associated with the current Issue because I feel that the text and the shortcut accelerator are coupled elements and whose stylings affect each other as a whole on the parent menu, i.e. say `Edit`, because the width of the entire menu-list should accommodate the largest text of the child menu-item.
