### ISSUE TITLE
Styling partly broken in Safari on iOS

### ISSUE THREAD

**Issue by 266-750Balloons** [khang-nd/7.css#4]
![IMG_4567 - Copy](https://user-images.githubusercontent.com/79549730/114770937-dc91f780-9d20-11eb-8c39-7547833ce0bd.jpeg)
When opening a file that uses 7.css, including the documentation, the window pane buttons are too small and missing their icons. The screenshot showing the issue occurring in documentation is attached.

Using iPhone 8 with iOS 14.4.2

**Comment by khang-nd** [comment]
Thank you for reporting, I did not have an iOS device to test this, but I will find some way to see how this looks on them. If anyone is able to fix it, please be welcome.

**Comment by khang-nd** [comment]
Fixed.
