### ISSUE TITLE
Issue with tabs (easy fix)

### ISSUE THREAD

**Issue by 2lag** [khang-nd/7.css#52]
I'm not 100% certain, but I am pretty darn close to it, that [this](https://github.com/khang-nd/7.css/blob/1bef7e0089804a6159d5bb37cb1dcd4a30375965/gui/_tabs.scss#L30) line in the code is what is causing a 1 pixel offset between the tab's end (while selected), and the lower window that the tab is meaning to enable. As seen here: 
![image](https://user-images.githubusercontent.com/96544487/201471606-adbb5757-b09f-4288-a7f1-88ca84c8d1ac.png)

**Comment by 2lag** [comment]
Also, I know it's really nitpicking at this point, but this as well on the left side: 
![image](https://user-images.githubusercontent.com/96544487/201471652-464a660b-606c-470e-8cb4-7f0f1c2dfa0a.png)

I believe this is caused by [this](https://github.com/khang-nd/7.css/blob/1bef7e0089804a6159d5bb37cb1dcd4a30375965/gui/_tabs.scss#L13) line of code.

**Comment by 2lag** [comment]
If it would be more convenient, I can tinker and submit a pull request. Just let me know if this is something intended or truly a bug because I can always create my own branch to fix the issue but that would be a little silly for something so small. Thank you in advance!

**Comment by khang-nd** [comment]
Hi @2lag, thanks for pointing them out, to reply:

> I'm not 100% certain, but I am pretty darn close to it, that [this](https://github.com/khang-nd/7.css/blob/1bef7e0089804a6159d5bb37cb1dcd4a30375965/gui/_tabs.scss#L30) line in the code is what is causing a 1 pixel offset between the tab's end (while selected), and the lower window that the tab is meaning to enable. As seen here: ![image](https://user-images.githubusercontent.com/96544487/201471606-adbb5757-b09f-4288-a7f1-88ca84c8d1ac.png)

I would assume that most of the time, the tab panel width should always be wider than the tab navigation, otherwise, something is not right with that tab's content, though with that said, it is still indeed a bug.



> Also, I know it's really nitpicking at this point, but this as well on the left side: ![image](https://user-images.githubusercontent.com/96544487/201471652-464a660b-606c-470e-8cb4-7f0f1c2dfa0a.png)
> 
> I believe this is caused by [this](https://github.com/khang-nd/7.css/blob/1bef7e0089804a6159d5bb37cb1dcd4a30375965/gui/_tabs.scss#L13) line of code.
> 
> Edit: It fills the gap when selected, so I'm assuming it's a bug not a feature

I'll just answer this with a screenshot of an actual tab:

![image](https://user-images.githubusercontent.com/55619201/201503635-34a7a3d9-039e-495e-940a-a995e0fae5e7.png)

Also, there's no such thing as a silly or small fix, every contribution counts and is appreciated, that's the nature of OSS from my perspective 🙂

**Comment by 2lag** [comment]
I'm glad I could point that out! Do you think an optimal solution would be to implement that same spacing that you showed here on the left side, but to the right side as well? I'm using variable sizing on my windows for my website so that may be the cause of this issue with the tab styling. May also be replicable by adding a lot of tabs/having long tab names.
> ![image](https://user-images.githubusercontent.com/96544487/201503947-231e8609-a919-4ca7-96c4-4ac2a977adde.png)

Side note though: I absolutely love your perspective on these things, I'll definitely tinker around with it and see what I can find! Thank you so much for the amazing words!

**Comment by khang-nd** [comment]
Yup, agreed. That sounds like a good and appropriate solution 🙂 Thanks mate.

**Comment by 2lag** [comment]
#55 Going to close this, can't wait to hear from you!

**Comment by khang-nd** [comment]
Looking good, thanks mate :)
