### ISSUE TITLE
Issue with toggling between Tabs

### ISSUE THREAD

**Issue by jomaaj** [khang-nd/7.css#56]
I copied the code directly into repl.it for "Another window with contents" - the example which has a window body with three tabs (music, dogs, food). 

For some reason, when I click on the other tabs (Dogs, Food), the content doesn't toggle to the content designated to those tabs/buttons. It just stays fixed on the "Music" content. 

I tried the same thing with copying the two "Tabs" code snippets, and I get the same issue. Clicking any of the other tabs does nothing - the content stays static. 

I know I've imported the 7.css file correctly because all of the other code snippets work (i.e. buttons, menu bars, etc.).

Has anyone had this issue? Anyone know how to fix this?

**Comment by khang-nd** [comment]
Hello @jomaaj, please refer to this #15

**Comment by jomaaj** [comment]
Thanks - I added the code from that script.js file, and it's still not working. Do i need to add any code within my index.html file that somehow calls the script.js file? Sorry I'm an amateur :/

**Comment by khang-nd** [comment]
No worries, we all are :) You're correct, you need to add a reference to the script, you can have a look [here ](https://github.com/khang-nd/7.css/blob/main/docs/index.html.ejs#L120).

**Comment by jomaaj** [comment]
Thank you! That worked.
