### ISSUE TITLE
(question) Is it possible to use the 7.css library with B00merang-Project?

### ISSUE THREAD

**Issue by ghost** [khang-nd/7.css#57]
Hi everyone.

Is it possible to use the [7.css](https://github.com/khang-nd/7.css) library with [B00merang-Project](https://github.com/B00merang-Project/discussion/discussions/2)?

*What do you all think of this idea?*

**Comment by khang-nd** [comment]
Probably. Idk, I don't use Linux 🤷‍♂️

**Comment by khang-nd** [comment]
Yea sure, I assigned an MIT license, so you can use it however you like.

**Comment by khang-nd** [comment]
I'm no license expert, but apparently, the license compatibility is ok, as you are trying to use an MIT-licensed project **_in_** a GPL one, not the other way around.
