### ISSUE TITLE
Will you add more features

### ISSUE THREAD

**Issue by baiyuxiong** [khang-nd/7.css#7]
Hi,
This is an awesome project. will you add more features?

1、layout support: flex, grid,
2、more components : toolbars, table, group box, icons

**Comment by khang-nd** [comment]
Hello, thanks for paying interest. Definitely, I will if there are more demands :)

**Comment by bevinhex** [comment]
I wonder how much work it needs for combining this with bootstrap, I see someone combined bootstrap4 with win95

**Comment by khang-nd** [comment]
Closing this issue as I have no plan for layout support. Toolbars, groupbox are implemented. Table will be addressed as part of the list view component (#73). Icons... 🤷‍♂️
