### ISSUE TITLE
Add list view/table component

### ISSUE THREAD

**Issue by khang-nd** [khang-nd/7.css#73]
Design guidelines: https://learn.microsoft.com/en-us/windows/win32/uxguide/ctrl-list-views

**Comment by ippezshelby** [comment]
Hello, Wondering if this table view was added already or there is PR for it... Thanks and regards

**Comment by khang-nd** [comment]
Hi, nope, this feature request is still open and untouched.

**Comment by k-usama1495** [comment]
When it will be released?

**Comment by k-usama1495** [comment]
Hi @khang-nd
I have taken your css and I have made a table which show a data
![Uploading Screenshot 2024-06-29 at 4.12.37 PM.png…]()

**Comment by khang-nd** [comment]
Hi @k-usama1495, that looks good, however, I don't think what you have there resembles the actual design close enough.

![](https://learn.microsoft.com/en-us/windows/win32/uxguide/images/ctrl-list-views-image6.png)

**Comment by k-usama1495** [comment]
@khang-nd @lfuelling thanks
