### ISSUE TITLE
Tabs aren't working properly

### ISSUE THREAD

**Issue by faeriemachine** [khang-nd/7.css#79]
Working on a personal webpage, and I wanted to let you know that I haven't been able to get my tabs to work properly in case this is an issue on your end!! I took the code straight from your 7.css webpage, and I can't seem to switch over from one tab to the other. If this is my fault though then please feel free to disregard this, I just figured I'd create an issue just in case it's something you need to fix :)

![GIF 2023-10-08 7-17-10 PM](https://github.com/khang-nd/7.css/assets/147113861/58b33df3-2c61-4de1-b2cc-17d2b246e66b)
![Screenshot_103](https://github.com/khang-nd/7.css/assets/147113861/9229ca82-e319-4426-820e-8ab63fcb3945)

**Comment by khang-nd** [comment]
Hi @faeriemachine, please see #15.
