### ISSUE TITLE
Input Text Cut Off in Safari 14

### ISSUE THREAD

**Issue by tkw1536** [khang-nd/7.css#8]
Thank you for this great library. 

I noticed that when loading the documentation page on OS X using Safari 14, the text entered into input boxes is cut off at the bottom:

<img width="770" alt="Safari 14 Broken Text Input" src="https://user-images.githubusercontent.com/2923242/122700600-e4ec3e80-d24b-11eb-8ef8-b6a2b79d4511.png">

The same problem occurs on iOS Safari. 

I've investigated a bit and the problem seems to be related to [this line height property](https://github.com/khang-nd/7.css/blob/8383ff43d59c2a17b744f2f0ed420ce11f621605/gui/_forms.scss#L61). Disabling this `line-height` property via  Developer Tools seems to fix the issue: <img width="762" alt="Safari 14 Fixed Input Line" src="https://user-images.githubusercontent.com/2923242/122700933-82e00900-d24c-11eb-9923-1501a927c056.png">

**Comment by khang-nd** [comment]
Hey @tkw1536, thank you for pointing that out. Will come back to this once I have time.

**Comment by khang-nd** [comment]
Fixed with commit 6ee8bd7ebcf4a7584fbbadd78b0a79a6370198b3.
