### ISSUE TITLE
Focus Outline Behaviour

### ISSUE THREAD

**Issue by hohaicongthuan** [khang-nd/7.css#83]
Hey @khang-nd, the dotted focus outline only appears when the UI is navigated using the keyboard (i.e. by pressing <kbd>Tab</kbd> or <kbd>Shift</kbd>+<kbd>Tab</kbd>). This behaviour can be achieved by using the [`:focus-visible`](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible) pseudo-class. I can fix it if you want.

![Screenshot_20231030_142424](https://github.com/khang-nd/7.css/assets/20926690/b0f6bbf5-c23d-498f-a648-ca81b159bc3e)

**Comment by khang-nd** [comment]
That would be awesome 👍
