### ISSUE TITLE
Im not surre if is a Issue.....

### ISSUE THREAD

**Issue by bsdrago** [khang-nd/7.css#85]
hey! great work with 7.css. but IM facing some problem. Not Sure why.
When I use your examples , e.g [Tabs](https://khang-nd.github.io/7.css/#tabs) works fine in my browser. (Firefox 122)

But if I copy the example and try to use it , e. g, [HERE](https://www.optimusmundi.com.br/test/), my tabs DOESNT Work.

Im not sure if im doing something wrong. Could you help me ? 

Its strange, because the is no JS in the code, so.....

Thanks for any help!

**Comment by bsdrago** [comment]
My mistake. I don't know why I thought css should work without js. After looking on the examples page, I realized that you do this using .js. Sorry for my mistake. =)

**Comment by bsdrago** [comment]
My mistake. I don't know why I thought css should work without js. After looking on the examples page, I realized that you do this using .js. Sorry for my mistake. =)

**Comment by khang-nd** [comment]
Glad you figured it out 🙂
