### ISSUE TITLE
Tabs not working

### ISSUE THREAD

**Issue by SkyKrye** [khang-nd/7.css#87]
I can't get tab switching to work, I know this issue is marked as solved but I tried to add css and js both into it, and still the tabs weren't clickable, the thing is that devtools wasn't marking any errors in the code either, but the js just didn't seem to work at all.

**Comment by khang-nd** [comment]
If you're asking about an issue in your code, provide the code. Sorry if it sounds harsh but it's a very fundamental approach in such case.

**Comment by SkyKrye** [comment]
It works now! Yes I did check those issues, but the problem was that for some reason the js wasn't working, I refined my code a bit and it works now, thank you, and also you did a GREAT job at recreating such a faithful and beautiful UI!!!!!
