### ISSUE TITLE
Scrollbar Suddenly Not Showing Up

### ISSUE THREAD

**Issue by wenxich** [khang-nd/7.css#92]
I have a WebKit-based browser, and I've added a has-scrollbar class to certain containers, but the custom scrollbar isn't working anymore. Unsure of why this was happening because I recall it working before before (I can still see the scrollbar on 7.css's page). Is anyone else experiencing the same issue?

For reference I have it added as a class of an article tag:

```
<article class="has-scrollbar" hidden id="art" role="tabpanel" style="margin-bottom: 0">
...
</article>
```

I wonder if it's because I'm using an article tag instead of a div tag? Is there another way to have the scrollbar show up for articles? Thanks.

**Comment by khang-nd** [comment]
Hey, I can't really help without further context. Would be helpful if you could elaborate more on "custom scrollbar isn't working anymore", e.g. does the default scrollbar appear in place of the custom one? or there's no scrollbar whatsoever? is the scroll region scrollable as expected...

**Comment by wenxich** [comment]
Hi, sorry for the vagueness in the initial post! I should have provided more context.

The default scrollbar appears in place of the custom one. The scroll region is scrollable as expected. On a separate part of the site, the scrollbar works as intended when "has-scrollbar" is added as a class to a div tag, like in the guide:

```
<div class="has-scrollbar" style="width: 300px; height: 150px; overflow: auto">
  Lorem ipsum dolor sit amet...
</div>
```

For this particular scenario, though, I have a container with tags, so something more like:

```
<div class="window-body has-space">
                <menu aria-label="Window with Tabs" role="tablist">
                    <button aria-controls="introduction" aria-selected="true" role="tab">Intro</button>
                    <button aria-controls="research" role="tab">Research</button>
                    <button aria-controls="art" role="tab">Art</button>
                </menu>
                <article class="has-scrollbar" id="introduction" role="tabpanel" style="margin-bottom: 0">
                    [intro text]
                </article>
                <article class="has-scrollbar" hidden id="research" role="tabpanel" style="margin-bottom: 0">
                    [research text]
                </article>

                <article class="has-scrollbar" hidden id="art" role="tabpanel" style="margin-bottom: 0">
                    [art text]
                </article>
</div>
```
What does work is adding a "has-scrollbar" class to the parent div, but then we end up with something like this:

<img width="302" alt="Screenshot 2024-05-25 at 1 13 50 PM" src="https://github.com/khang-nd/7.css/assets/92760430/51c54ff3-6fd0-4595-8ad7-67b9cbb72eb3">
<img width="301" alt="Screenshot 2024-05-25 at 1 14 01 PM" src="https://github.com/khang-nd/7.css/assets/92760430/c756d331-439a-43ed-8333-7d8ed4c7b7b6">

Where the scrollbar shows up, but when there isn't a scroll needed (like for Intro) there is a container for it, and when there is a scroll needed, it's outside the article container.

I'd appreciate being able to have something like this instead:

<img width="303" alt="Screenshot 2024-05-25 at 1 16 32 PM" src="https://github.com/khang-nd/7.css/assets/92760430/f77a55db-cc6d-4ae9-bc7f-c89d4d91a148">

Which I tried to execute with the initial code (first codeblock), but it didn't work (only the default scrollbar shows up).

Let me know if you need any additional information, and I really appreciate you looking at this.

**Comment by khang-nd** [comment]
I made a minimal [CodeSandbox](https://codesandbox.io/p/sandbox/7-css-scrollbar-xtlk5h?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwocc0er0006356kztte1wkb%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwocc0er0002356kffwu4ygd%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwocc0er0003356kxeqsho3q%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwocc0er0005356kqht5de2p%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwocc0er0002356kffwu4ygd%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwocc0eq0001356kf2lqhft3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clwocc0er0002356kffwu4ygd%2522%252C%2522activeTabId%2522%253A%2522clwocc0eq0001356kf2lqhft3%2522%257D%252C%2522clwocc0er0005356kqht5de2p%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwocc0er0004356k3mjknr8z%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clwocc0er0005356kqht5de2p%2522%252C%2522activeTabId%2522%253A%2522clwocc0er0004356k3mjknr8z%2522%257D%252C%2522clwocc0er0003356kxeqsho3q%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clwocc0er0003356kxeqsho3q%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) based on what you've provided and the scrollbar shows up still. 

Can you have a look and check with your code to see if anything is missing?

**Comment by wenxich** [comment]
Ah, this helped me figure it out! I had another div around that codeblock:

```
<div class="window active glass" id="about">
            <div class="title-bar">
                <div class="title-bar-text">About Me</div>
                <div class="title-bar-controls">
                    <button aria-label="Close"></button>
                </div>
            </div>
[what you had copied]
</div>
```

To mimic a window. I had applied "overflow: scroll" to the outer window at some point, which made the default scrollbar show up as it was scrolling on the outer window and not the inner article.

Thank you so much for helping me take a look at this and sorry for the trouble.
