### ISSUE TITLE
windows 10 or dark mode possibility? 

### ISSUE THREAD

**Issue by mmiscool** [khang-nd/7.css#95]
Hello, 
I found the way you did your project extremely nice. The fact it only uses CSS to do all that fancy stuff really knocks it out of the park. 

I would like to ask if there is any chance you might make a dark mode version or a windows 10 version that supports dark mode. Windows 10 is now around 10 years old and EOL. 

If that is not some thing you might be interested in could you suggest any other CSS only UI toolkits that have any thing similar to this?

I have 40$ burning a hole in my pocket for a dark mode on this if you were able to make one within the next 2 weeks.

**Comment by khang-nd** [comment]
Hello @mmiscool, thank you, glad to hear you find the project useful. Personally, I've had no time to keep working on this project so I cannot accept your request, however, @hohaicongthuan is keen to take this up if you're willing to offer him this chance (he's also made impactful contributions to the project as I've reviewed his PRs).

Please reach out to him via his email (as shared on his Github profile) and share your requirements and expectations. Have a good time collaborating 🙂
