### ISSUE TITLE
Use <datalist> for Combo Box

### ISSUE THREAD

**Issue by CiberNin** [khang-nd/7.css#96]
As I understand, the <datalist> & <option> tags are the semantic way to markup a combo box these days.

**Comment by khang-nd** [comment]
<img width="819" alt="image" src="https://github.com/user-attachments/assets/0ea987b4-6263-4f32-9350-78f36214a753">
That and I don't think it's possible to achieve the combobox styling on top of that datalist element. Feel free to elaborate otherwise.
